#!/bin/bash
set -e

port=3999

./tests/server.js $port &>/dev/null &
pid=$!
trap "kill $pid" INT EXIT

while ! lsof -i :$port >/dev/null; do
  sleep 0.05
done

exec phantomjs tests/runner.coffee \
  "http://localhost:${port}/tests/qunit.html"
